### ISSUE TITLE
运行出现关于spacy和cymem的错误？

### ISSUE THREAD

**Issue by YeNiTing** [ShomyLiu/pytorch_bert_elmo_example#6]
请问一下spacy和cymem的版本是多少？我运行出现这个错误：
e "cymem.pxd", line 4, in init spacy.matcher.matcher
AttributeError: module 'cymem.cymem' has no attribute 'PyMalloc'

**Comment by ShomyLiu** [comment]
你好！ 不好意思，忘记回复了。 我的spacy版本如下：
```
spacy 2.1.9
```
不过你的那个问题可以参考下这个solution：
https://stackoverflow.com/questions/53122687/spacy-fails-to-run-with-error-cymem-cymem-has-no-attribute-pymalloc

**Comment by YeNiTing** [comment]
> 你好！ 不好意思，忘记回复了。 我的spacy版本如下：
> 
> ```
> spacy 2.1.9
> ```
> 
> 不过你的那个问题可以参考下这个solution：
> https://stackoverflow.com/questions/53122687/spacy-fails-to-run-with-error-cymem-cymem-has-no-attribute-pymalloc

我之前有尝试这个网站的解决方案，可是最终问题还没有解决。

**Comment by ShomyLiu** [comment]
我觉得应该是python环境问题， 建议使用virtual env 或者 conda等创建新的虚拟环境，重新安装这些库，再试试。

**Comment by YeNiTing** [comment]
> 我觉得应该是python环境问题，建议使用virtual env或conda等创建新的虚拟环境，重新安装这些库，再试试。

感谢提供解决思路，我有尝试过conda创建新虚拟环境，改spacy和cymem以及thinc版本，最终问题都没有得到解决，想问一下您的cymem库的版本？

**Comment by ShomyLiu** [comment]
我没有主动安装过cymem, 是安装spacy的时候依赖安装，版本为: 2.0.3

**Comment by YeNiTing** [comment]
> 我没有主动安装过cymem, 是安装spacy的时候依赖安装，版本为: 2.0.3

十分感谢您的回答，最后问一下您的python版本是多少？

**Comment by ShomyLiu** [comment]
你好，我的python环境是3.6

**Comment by YeNiTing** [comment]
> 你好，我的python环境是3.6

您好，我最终解决了这个问题，是我终端运行时未选择虚拟环境，我最初的做法
C:\Users\YNT\Desktop\重要文件夹\数据集\EMLo相关\pytorch_bert_elmo_example-master>python main.py train --emb_method='emlo'
--enc_method='cnn'
后来发现是我没有激活虚拟环境，然后激活虚拟环境后
(ynt2) C:\Users\YNT\Desktop\重要文件夹\数据集\EMLo相关\pytorch_bert_elmo_example-master>python main.py train --emb_method=
'emlo' --enc_method='cnn'
然后之前的错误得到解决。
现在又出现另一个错误：
Traceback (most recent call last):
  File "main.py", line 107, in <module>
    fire.Fire()
  File "D:\software\Anaconda3\envs\ynt2\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\software\Anaconda3\envs\ynt2\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "D:\software\Anaconda3\envs\ynt2\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main.py", line 48, in train
    model = Model(opt)
  File "C:\Users\YNT\Desktop\重要文件夹\数据集\EMLo相关\pytorch_bert_elmo_example-master\model.py", line 26, in __init__
    self.encoder = Encoder(opt.enc_method, self.word_dim, opt.hidden_size, opt.out_size)
  File "D:\software\Anaconda3\envs\ynt2\lib\site-packages\torch\nn\modules\module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Model' object has no attribute 'word_dim'

**Comment by ShomyLiu** [comment]
self.word_dim -> self.opt.word_dim

**Comment by YeNiTing** [comment]
> self.word_dim -> self.opt.word_dim

word_dim似乎不是您配置文件中定义的参数，您项目的代码原文：
        if opt.emb_method == 'elmo':
            self.init_elmo()

 self.encoder = Encoder(opt.enc_method, self.word_dim, opt.hidden_size, opt.out_size)#出现错误的代码行

 def init_elmo(self):
        '''
        initilize the ELMo model
        '''
        self.elmo = Elmo(self.opt.elmo_options_file, self.opt.elmo_weight_file, 1)
        for param in self.elmo.parameters():
            param.requires_grad = False
        self.word_dim = self.opt.elmo_dim
是因为word_idm定义顺序的问题吗？

**Comment by ShomyLiu** [comment]
前面记错了。
每次init的时候，会定义self.word_dim   之后才会定义encoder， 你是有修改源码吗？  我这边重新clone没有问题呀

**Comment by YeNiTing** [comment]
> 前面记错了。
> 每次init的时候，会定义self.word_dim 之后才会定义encoder， 你是有修改源码吗？ 我这边重新clone没有问题呀

我这边没有修改源码，非常感谢你的解答，我找到我出现错误的原因了，是因为我在命令行运行时emb_method=‘elmo’拼写错误。
